# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4211065b61675dbec54406b246cede6d1c0d88425eb913ec43cdbd26c64ff6e5f6b57b5c2287ea2ec284e7116f0e06b4023a5356a2f49b3852b9567149633b1c

test:
  secret_key_base: 94159b2c4aee2ff6eb9d259fc2795295cd0ba0f0714d7905bcfb7ea1571b186e7a1561d17a0e00b98365014900432ca8e032a3bc0c6fc0f64e24f20dea3dbef5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
